name: Auto-scrape & publish master CSV

on:
  schedule:
    # Every 30 minutes
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # we will use PAT below
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scrapers & build master CSV
        run: |
          python shopify_generic_scraper.py
          python magento_generic_scraper.py || true  # tolerate failures
          python direct_retailer_scraper.py || true
          python combine_prices.py
      - name: Commit updated CSV
        run: |
          git config user.name "cheapammo-bot"
          git config user.email "actions@github.com"
          git add all_prices.csv
          if ! git diff --cached --quiet; then
            git commit -m "github-action: update all_prices.csv $(date -u '+%Y-%m-%d %H:%M')"
          fi
      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
